name: Daily Property Notification

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour at 00 minutes (e.g., 01:00, 02:00, etc.)
  workflow_dispatch:  # optional: lets you trigger manually


jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar
      
      - name: Run notification script
        run: python property_notification.py
