name: Daily Rental Check-in/Check-out Notifications

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour at 00 minutes (e.g., 01:00, 02:00, etc.)
  workflow_dispatch:  # optional: lets you trigger manually

jobs:
  send_notifications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests icalendar
        
    - name: Run notification script
      run: python rental_notifications.py
