name: Daily iCal to Telegram

on:
  schedule:
    # Runs at 11:00 UTC every day
    - cron: '0 11 * * *'
  workflow_dispatch:
    # Lets you run the workflow manually from GitHub as well

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo
      - name: Check out repo
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or 3.10, whichever you prefer

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install requests icalendar

      # 4) Run your script
      - name: Run script
        run: |
          python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
